version: '3.9'

services:
  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_DATABASE}

  postgres_test:
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_USER=testuser
      - POSTGRES_DB=testdb
    tmpfs:
      - /var/lib/postgresql/data  # No persistence for test DB

volumes:
  postgresdata: